import type { Metadata } from 'next'
import { Orbitron, Roboto } from 'next/font/google'
import './globals.css'

const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin']
})

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Hackathon-USP',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${orbitron.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
